---
title: "energy"
author: "Declan Oberlies"
date: "2026-02-10"
output: html_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
#loading packeges
library(readr)
library(dplyr)
library(ggplot2)
library(knitr)
library(plotly)
```

## Renewable Energy dataset

```{r, echo=FALSE, warning=FALSE, message=FALSE}
energy <- read_csv("../../data/IRENA data.csv", skip = 1)
#energy %>% head()
#View(energy)
```

## gapminder

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(gapminder)
#gapminder %>% head
#View(gapminder)
```

```{r, echo=FALSE, warning= FALSE, message=FALSE}
url <- 'https://nyc3.digitaloceanspaces.com/owid-public/data/co2/owid-co2-data.csv'
  
carbon <-
  read_csv(url) 
#carbon %>% head
#View(carbon)
```

## Levelized cost of energy

```{r, echo=FALSE, warning= FALSE, message=FALSE}
url <- 'https://raw.githubusercontent.com/ericmkeen/sewanee_esus/master/02_energy_sector/levelized-cost-of-energy.csv'
econ <- read_csv(url)
#econ %>% head()
#View(econ)
```

```{r,warning = FALSE, echo=FALSE}
ggplot(econ,
       aes(x = year, 
           y = cost,
           color = source)
       ) +
  geom_point() +
  geom_hline(yintercept = 0.05, lty = 2) +
  geom_hline(yintercept = 0.18, lty = 2) +
  annotate(geom= 'text',
           x=1990, 0.1, size = 5, label = 'Range of fossil\n fule costs')
  
```

```{r, echo=FALSE}
econ%>% 
  filter(year == 2020) %>%
  group_by(source) %>%
  summarize(cost = mean(cost, na.rm = TRUE)) %>%
  kable

```

```{r, echo=FALSE}
###FAILED GRAPH###
# using energy dataset
## find ranges 
#energy %>% pull(Year) %>% range()
#energy %>% pull(`Electricity statistics`) %>% range(na.rm = FALSE)
## join for continents
#energy_rn <- energy %>% 
  #rename(country = `Country/area`, year = Year)
#View(energy_rn)
#energy_join <- 
  #left_join(energy_rn, gapminder, by = c('year', 'country'))
#View(energy_join)
#energy_join <- energy_join %>% group_by(continent)
#energy_join %>%
  #filter(year == c(2000:2024))
## make faceted graph
#ggplot(energy_join,
       #aes(x = year,
           #y = `Electricity statistics`,
           #color = continent)) +
  #geom_path(size =1) +
  #facet_wrap(~Technology) +
  #scale_x_continuous(breaks = c(2000,2024)) +
  #scale_y_discrete(breaks = c(0, 10000))

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# gapminder
## new data frame
fig_1data <- 
  data.frame( lifeExp = gapminder %>%
                           group_by(year) %>% 
                summarize(mean(lifeExp, na.rm = TRUE),
                          mean(gdpPercap, na.rm = TRUE))) %>% 
  rename( year = lifeExp.year, 
          mean_lifeExp = lifeExp.mean.lifeExp..na.rm...TRUE.,
          mean_gdpPercap = lifeExp.mean.gdpPercap..na.rm...TRUE.)                
#View(fig_1data)

## make plot
scale_factor <- max(fig_1data$mean_gdpPercap) /
                max(fig_1data$mean_lifeExp)

ggplot(fig_1data,
       aes(x = year)) +
  geom_path(color = "green", 
            aes(y = mean_lifeExp)) +
  geom_path(color = "orange", 
            aes(y = mean_gdpPercap/scale_factor)) +
  scale_y_continuous(name = 'Mean Life Expectancy (green)', sec.axis = sec_axis(
      ~ . * scale_factor, 'Mean GDP Percapita in USD (orange)')) +
  labs(title = "Human Progress",
       subtitle = "Advances in human standard of living since 1950")

```

Since 1950, human standard of living has increased. On average, people are living longer and earning more money. This is due to...

-   Advances in medicine and healthcare

-   Advances in childbirth procedures

-   Advanced manufacturing

...and much more. All this advancement and progress has come at a cost.

```{r echo=FALSE, message=FALSE, warning=FALSE}
# carbon dataset
fig_2data <- 
  data.frame(carbon %>% 
               filter(country == "World") %>%
               group_by(year) %>% 
               summarise( totalCO2 = sum(cumulative_co2, na.rm = TRUE)))
#View(fig_2data)

## make graph
ggplot(fig_2data,
       aes(x = year, 
           y = totalCO2/1000)) +
  geom_point( size = .2) +
  geom_vline(xintercept = 1821, lty = 2.5 ) +
  annotate( geom = 'text',
            1816, 1000, angle = 90, label = 'first electric motor ') +
  geom_vline(xintercept = 1859, lty = 2.5 ) +
  annotate( geom = 'text',
            1854, 1000, angle = 90, label = 'first oil well ') +
  geom_vline(xintercept = 1882, lty = 2.5 ) +
  annotate( geom = 'text',
            1877, 1000, angle = 90, label = 'first power grid') +
  geom_vline(xintercept = 1950, lty = 2.5 ) +
  annotate( geom = 'text',
            1945, 1000, angle = 90, label = 'comericial plastic popularized') +
  labs(title = "Exponential Progress and Exponential Consiquences",
       y = "total CO2 emmited (thousands of tons)")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# energy dataset
#energy %>% pull(Year) %>% range
fig_3data <- data.frame(energy %>% 
  group_by(`Country/area`, Year) %>%
  summarize(total_energy = sum(as.numeric(`Electricity statistics`), na.rm = TRUE))) %>%
  filter(Year != 2024) %>%
  mutate(total_energy = total_energy/1000000)
fig_3trace <- 
  fig_3data %>%
  filter(Country.area %in% c('United States of America (the)', 'China', 'India')) %>%
  rename(Country = Country.area) 

#gap_filt <- gapminder %>%
  #filter(year %in% c(2000:2023)) %>%
  #rename( Country.area = country, Year = year)
#View(gap_filt)
#fig_3data <- left_join(fig_3data, gap_filt, by = c("Country.area", "Year"))
#fig_3data %>%
  #mutate(energyPercap = (total_energy/pop)) 
#View(fig_3data)

# make a grpah
ggplot(fig_3data,
       aes( x = Year,
            y = total_energy))+
  geom_point() +
  geom_path(data = fig_3trace, aes(color = Country), size =1) +
  labs(title = "Energetic Nations", y = "Total Energy (millions of GWh)")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# energy zoom in
#econ_filt <- 
  #econ %>%
  #filter( country %in% c('United States of America (the)', 'China', 'India'),
          #year %in% c(2000:2023))
#gap_filt <- gapminder %>%
  #filter(year %in% c(2000:2023), country %in% c('United States of America (the)', 'China', 'India'))
  
#fig_3trace <- 
  #fig_3trace %>%
  #rename(country = Country.area, year = Year)
#fig_4data <- left_join(fig_3trace, gap_filt, by = c("country", "year")) 
fig_4data <- energy %>%
  filter(`Country/area` %in% c('United States of America (the)', 'China', 'India')) %>%
  mutate(`Electricity statistics` = 
           as.numeric(na_if(`Electricity statistics`,"-"))) %>%
  mutate(`Electricity Generated` = `Electricity statistics`/1000) %>%
  filter(Technology != "Total renewable", Technology != "Total non-renewable")
  
#View(fig_4data)
# make a plot

fig.4 <- ggplot(fig_4data,
       aes(x = Year,
           y = `Electricity Generated`,
           color = Technology)) +
  geom_point() +
  geom_path() +
  facet_wrap(~`Country/area`, nrow = 3) +
  scale_y_continuous( breaks = c(1000, 3000,5000)) +
  labs( title = "",
        y = "Electricity Generation (thousands of GWh)") 

ggplotly(fig.4)
  
```
